import { ReactNode } from 'react'
import './globals.css'

export const metadata = {
  title: 'Harry Potter',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-black">{children}</body>
    </html>
  )
}
